# Generated by Django 3.2.4 on 2021-07-15 12:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210701_0100'),
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderLineProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_size', models.CharField(blank=True, max_length=2, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('lineitem_total', models.DecimalField(decimal_places=2, editable=False, max_digits=6)),
            ],
        ),
        migrations.RenameField(
            model_name='order',
            old_name='street_address1',
            new_name='address_line1',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='county',
            new_name='address_line2',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='street_address2',
            new_name='county_state',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='date',
            new_name='purchase_date',
        ),
        migrations.AddField(
            model_name='order',
            name='profile',
            field=models.CharField(default=django.utils.timezone.now, editable=False, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(editable=False, max_length=32, null=True),
        ),
        migrations.DeleteModel(
            name='OrderLineItem',
        ),
        migrations.AddField(
            model_name='orderlineproduct',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineitemorder', to='checkout.order'),
        ),
        migrations.AddField(
            model_name='orderlineproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
