# Generated by Django 3.2.4 on 2021-07-16 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20210715_1215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlineproduct',
            old_name='lineitem_total',
            new_name='lineproduct_total',
        ),
    ]
