# Generated by Django 3.2.4 on 2021-07-18 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_alter_orderlineproduct_lineproduct_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineproduct',
            name='lineproduct_total',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=6),
        ),
    ]
