# Generated by Django 3.2.4 on 2021-07-18 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_auto_20210718_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='product_size',
            field=models.IntegerField(blank=True, max_length=2, null=True),
        ),
    ]
