# Generated by Django 3.2.4 on 2021-07-27 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name_plural': 'Contact Us'},
        ),
        migrations.RenameField(
            model_name='contactus',
            old_name='contactus_message',
            new_name='cmessage',
        ),
        migrations.RenameField(
            model_name='contactus',
            old_name='contactus_subject',
            new_name='csubject',
        ),
        migrations.AddField(
            model_name='contactus',
            name='cdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactus',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
