# Generated by Django 3.2.4 on 2021-07-28 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210727_2025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='user',
            new_name='cuser',
        ),
    ]
