# Generated by Django 3.2.4 on 2021-07-29 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_contactus_cuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='cdate',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='contactus',
            old_name='cmessage',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='contactus',
            old_name='csubject',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='contactus',
            old_name='ctime',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='contactus',
            old_name='cuser',
            new_name='user',
        ),
    ]
