# Generated by Django 3.2.4 on 2021-07-25 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='review_date',
            new_name='rdate',
        ),
        migrations.RenameField(
            model_name='testimonial',
            old_name='user_message',
            new_name='rmessage',
        ),
        migrations.RenameField(
            model_name='testimonial',
            old_name='rating',
            new_name='rrating',
        ),
        migrations.RenameField(
            model_name='testimonial',
            old_name='user_test_title',
            new_name='rtitle',
        ),
        migrations.RenameField(
            model_name='testimonial',
            old_name='user_profile',
            new_name='uprofile',
        ),
    ]
