# Generated by Django 3.2.4 on 2021-07-29 23:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0003_auto_20210725_1231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='rmessage',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='testimonial',
            old_name='rrating',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='testimonial',
            old_name='rtitle',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='rdate',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testimonial',
            name='time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
