# Generated by Django 3.2.4 on 2021-07-30 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0004_auto_20210729_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='rating',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
