# Generated by Django 3.2.4 on 2021-07-01 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='colour',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.DecimalField(decimal_places=0, max_digits=6, null=True),
        ),
    ]
