# Generated by Django 3.2.4 on 2021-07-29 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_has_sold'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='imagefour',
            new_name='image_four',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='imagefour_url',
            new_name='image_four_url',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='imagethree',
            new_name='image_three',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='imagethree_url',
            new_name='image_three_url',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='imagetwo',
            new_name='image_two',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='imagetwo_url',
            new_name='image_two_url',
        ),
    ]
