# Generated by Django 3.2.4 on 2021-07-15 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210715_1911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image1',
            new_name='image_1',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='image2',
            new_name='image_2',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='image3',
            new_name='image_3',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='image4',
            new_name='image_4',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='image_url1',
            new_name='image_url_1',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='image_url2',
            new_name='image_url_2',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='image_url3',
            new_name='image_url_3',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='image_url4',
            new_name='image_url_4',
        ),
    ]
