# Generated by Django 3.2.4 on 2021-07-15 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20210715_2018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image_four',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='image_url_four',
            new_name='image_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_one',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_three',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_two',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_url_one',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_url_three',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_url_two',
        ),
    ]
