# Generated by Django 3.2.4 on 2021-07-15 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20210715_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='imagefour',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='imagefour_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='imagethree',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='imagethree_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
